# Generated by Django 5.2.1 on 2025-07-16 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('give_date', models.DateTimeField(auto_now=True)),
                ('item_state', models.CharField(default='available', max_length=20)),
                ('give_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='give_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gat_app_item',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='item_image')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
            options={
                'db_table': 'gat_app_itemimage',
            },
        ),
        migrations.CreateModel(
            name='ItemTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_date', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('take_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gat_app_itemtaken',
            },
        ),
    ]
