# Generated by Django 5.2.1 on 2025-07-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('EL', 'Electronics'), ('FU', 'Furniture'), ('BK', 'Books'), ('CL', 'Clothing'), ('KI', 'Kitchenware'), ('TY', 'Toys & Games'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
